name: ChatPolls
version: 1.0.0
api-version: 1.13
description: Poll your players!
author: Dominic Feliton
main: com.dominicfeliton.chatpolls.ChatPolls
folia-supported: false
commands:
  chp:
    description: Prints ChatPolls version.
    aliases: [ chatpolls ]
    usage: ยง4/chp
    permission: chatpolls.chp
    permission-message: ยง4You do not have permission to run this command.
  chpl:
    description: Changes a player's localization.
    aliases: [ chatpollslocal, chatpollsl ]
    usage: ยง4/chpl (playerName) (languageName)
    permission: chatpolls.chpl
    permission-message: ยง4You do not have permission to run this command.
permissions:
  chatpolls.*:
    description: Gives access to all ChatPolls commands.
    children:
      chatpolls.chp: true
      chatpolls.chpl: true
      chatpolls.chpl.otherplayers: true
    default: op
  chatpolls.chp:
    description: Gives access to /chp.
    default: true
  chatpolls.chpl:
    description: Gives access to /chpl.
    default: true
  chatpolls.chpl.otherplayers:
    description: Gives access to /chpl on other players.
    default: op